import React from 'react';
import './GamingPage.css';
import GamingHeader from '../GamingHeader/GamingHeader';
import GamingCard from '../GamingCard/GamingCard';
import GamingRecommendedCard from '../GamingRecommendedCard/GamingRecommendedCard';
import GamingShorts from '../GamingShorts/GamingShorts';


const GamingPage = () => {
  return (
      <div className='gamingPage'>
          <div className='gamingHeaderSection'>
          <GamingHeader
              image='https://yt3.ggpht.com/NkyduaNYnXjfB10iu9wudGpe8sA1acTrBvK0Fiuaz2r14KFI9-CyPpKgXD6xUL049j4vOVL4=s176-c-k-c0x00ffffff-no-rj-mo'
              channel='Gaming'
              subscriptions='92.9'
              button='SUBSCRIBE'
          />
          </div>

          <header className='gamingCard__header'>
              <h4>Top live games</h4>
              <p className='gamingCard'>Auto-generated by YouTube</p>
          </header>
          <div className='gamingPageSection'>
            <GamingCard />
            <hr className='gamingPageSection__hr' />
            <header className='gamingRecommendedCard__header'>
                <h4>Recommended</h4>
                <p>Based on your Subscriptions and History</p>
            </header>
            <div className='gamingRecommended'>
               <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/cYuD10oJ648/mqdefault.jpg'
                  title='SNEAKO Has Had The Same Message for a Decade!'
                  channel='SHNEAKO'
                  verified
                  views='217'
                  timestamp='3 months ago'
                />
               <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/FeqaTVS1qj8/maxresdefault.jpg'
                  title='Ninja Quits Streaming'
                  channel='Asmongold TV'
                  verified
                  views='705'
                  timestamp='1 day ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/09k2f8RtvFQ/maxresdefault.jpg'
                  title='FALL GUYS BUT I CAN ONLY COME LAST...'
                  channel='MM7Games'
                  verified
                  views='392'
                  timestamp='1 day ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/nYpqG-lxj8A/maxresdefault.jpg'
                  title='Deji EXPOSES Fousey For Saying This To Him...'
                  channel='CHZ'
                  verified
                  views='40'
                  timestamp='3 days ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/hkY6fvvyYw8/maxresdefault.jpg'
                  title='KENNY DIDNT WANT THIS 1v1 ON YOUTUBE!'
                  channel='CashNastyReacts'
                  verified
                  views='198'
                  timestamp='3 days ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/2B2hosM02F0/maxresdefault.jpg'
                  title='SNEAKO Reacts to Andrew Tate Funny Moments!'
                  channel='SHNEAKO'
                  verified
                  views='327'
                  timestamp='3 months ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/nm-O8X5YBfQ/maxresdefault.jpg'
                  title='Andrew Tate Back Saves Life Of Teenage Gamers Than...'
                  channel='Klero'
                  verified
                  views='49'
                  timestamp='6 days ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/_H8N-RN_WTg/maxresdefault.jpg'
                  title='SNEAKO, Destiny, and Myron Fresh and Fit HEATED Debate'
                  channel='SHNEAKO'
                  verified
                  views='101'
                  timestamp='10 days ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/0ZXIIEsgTiI/maxresdefault.jpg'
                  title='Ashes of Creation World Tripled In Size, But Will It Fe...'
                  channel='Asmongold TV'
                  verified
                  views='114'
                  timestamp='1 day ago'
                />
                <GamingRecommendedCard
                  image='https://i.ytimg.com/vi/yWr3OGC5t7s/maxresdefault.jpg'
                  title='SNEAKO Reacts To IShowSpeed Getting...'
                  channel='SHNEAKO'
                  verified
                  views='429'
                  timestamp='2 weeks ago'
                />
            </div>
                <hr className='gamingPageShorts__hr' />
                <header className='gamingRecommendedCard__shortsHeader'>
                    <img 
                      src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Youtube_shorts_icon.svg/1649px-Youtube_shorts_icon.svg.png'
                      alt='youtube shorts'
                      className='gamingRecommendedCard__shortsLogo'
                    />
                    <p>Shorts</p>
                </header>
                <div className='gamingRecommended__shorts'>
                    <GamingShorts />
                </div>
          </div>
      </div>
  );
};

export default GamingPage;